name: Run pre-commit hooks

on:
  push:
    branches: [ main ]
  workflow_call:
  pull_request:

env:
  UV_LOCKED: true  # Assert that the `uv.lock` will remain unchanged

jobs:
  precommit:
    name: Run pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          # It is considered best practice to pin to a specific uv version.
          version: "0.9.29"
          python-version: '3.13'

      - name: Install the project
        run: uv sync

      - name: Cache pre-commit hooks and environments
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run remaining pre-commit hooks
        run: uv run pre-commit run --all-files
